.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md, CODE_OF_CONDUCT.md
please feel free to make any changes
=> Proposal of issue, PR templates and code of conduct

src/main/kotlin/org/openpolicyagent/ideaplugin/ide/todo/RegoLexerBasedTodoIndexer.kt, src/main/kotlin/org/openpolicyagent/ideaplugin/ide/todo/RegoTodoIndexPatternBuilder.kt, src/main/kotlin/org/openpolicyagent/ideaplugin/lang/psi/RegoTokenType.kt, src/main/resources/META-INF/plugin.xml, src/test/kotlin/org/openpolicyagent/ideaplugin/ide/todo/RegoTodoTest.kt
=> Index TODO in rego comment

build.gradle.kts, src/main/kotlin/org/openpolicyagent/ideaplugin/ide/actions/CheckAction.kt, src/main/kotlin/org/openpolicyagent/ideaplugin/ide/actions/CheckDocumentAction.kt, src/main/kotlin/org/openpolicyagent/ideaplugin/ide/actions/InstallOPA.kt, src/main/kotlin/org/openpolicyagent/ideaplugin/ide/actions/TestAction.kt, src/main/kotlin/org/openpolicyagent/ideaplugin/ide/actions/TraceSelectionAction.kt, src/main/kotlin/org/openpolicyagent/ideaplugin/ide/actions/utils.kt, src/main/kotlin/org/openpolicyagent/ideaplugin/ide/extensions/FileLineFilter.kt, src/main/kotlin/org/openpolicyagent/ideaplugin/ide/extensions/OPAActionToolWindow.kt, src/main/kotlin/org/openpolicyagent/ideaplugin/ide/extensions/RegoModuleBuilder.kt, src/main/kotlin/org/openpolicyagent/ideaplugin/ide/extensions/RegoModuleType.kt, src/main/kotlin/org/openpolicyagent/ideaplugin/lang/psi/RegoFile.kt, src/main/kotlin/org/openpolicyagent/ideaplugin/opa/tool/OpaActions.kt, src/main/resources/META-INF/plugin.xml
Added function to look for input.json in project root (in ActionUtils), same as vscode does, can use for opa eval as well
=> Tracesel - adding trace of selected text to code menu, same format as opa check/test 

.github/workflows/test.yml, docs/devel/setup_development_env.md, hack/check-license.sh, src/main/kotlin/org/openpolicyagent/ideaplugin/ide/actions/InstallOPA.kt, src/main/kotlin/org/openpolicyagent/ideaplugin/ide/actions/TestAction.kt, src/main/kotlin/org/openpolicyagent/ideaplugin/ide/actions/TraceSelectionAction.kt, src/main/kotlin/org/openpolicyagent/ideaplugin/ide/extensions/FileLineFilter.kt, src/main/kotlin/org/openpolicyagent/ideaplugin/ide/extensions/OPAActionToolWindow.kt, src/main/kotlin/org/openpolicyagent/ideaplugin/ide/highlight/RegoHighlighterAnnotator.kt
=> check licence

src/main/kotlin/org/openpolicyagent/ideaplugin/ide/typing/RegoBraceMatcher.kt, src/main/resources/META-INF/opa-core.xml, src/test/kotlin/org/openpolicyagent/ideaplugin/ide/typing/RegoBraceMatcherTest.kt
Implements a `PairedBraceMatcher` to auto close brace, parenthesis and bracket 
Fixes #23
=> Editing: auto closing brace, bracket and parenthesis

README.md
Update installation instruction to use stable channel. 
I keep images of the  images that explain how to add a custom repository because we will need it, for the nightly channel
=> readme: update installation instruction to use stable channel

.github/workflows/test.yml
Cache gradle dependencies between run.
check the signature of the Gradle wrapper. More info at [https://github.com/gradle/wrapper-validation-action](https://github.com/gradle/wrapper-validation-action)
ref #5
=> Cache dependencies

gradle.properties
update version of the plugin for next release.  (to avoid to unintentionally override the current one)
Fixes #
=> set version for next release

gradle.properties
when I made the last release I forgot to push the gradle properties with the new version . That why the version is increased by 2
Fixes #
=> gradle.properties set next version

.github/workflows/test.yml, build.gradle.kts, docs/devel/setup_development_env.md, gradle-201.properties, gradle-202.properties
Run [intellij-plugin-verifier](https://github.com/JetBrains/intellij-plugin-verifier) to check plugin binary compatibility in github action
1. update `org.jetbrains.intellij` Gradle plugin because the new version offers a task to run the plugin verifier. Consequently, remove the `ideaDependencyCachePath`customization which is not needed anymore.
2. add a job to run plugin verifier
Fixes #56
=> github action: verify plugin binary compatibility

gradle-201.properties, gradle-202.properties, src/test/kotlin/org/openpolicyagent/ideaplugin/lang/RegoParsingTestCaseBase.kt
=> Fix test macos and GitHub actions

src/main/kotlin/org/openpolicyagent/ideaplugin/ide/typing/RegoQuoteHandler.kt, src/main/resources/META-INF/opa-core.xml, src/test/kotlin/org/openpolicyagent/ideaplugin/ide/typing/RegoBraceMatcherTest.kt, src/test/kotlin/org/openpolicyagent/ideaplugin/ide/typing/RegoQuoteHandlerTest.kt, src/test/kotlin/org/openpolicyagent/ideaplugin/ide/typing/RegoTypingTestBase.kt
- add auto closing quote feature
- introduce an abstract base class for typing tests
Fixes #22
=> add auto closing quote feature

gradle-202.properties, src/main/grammar/Rego.bnf, src/main/grammar/RegoLexer.flex, src/test/kotlin/org/openpolicyagent/ideaplugin/ide/highlight/RegoSyntaxErrorAnnotatorTest.kt, src/test/resources/org/openpolicyagent/ideaplugin/lang/parser/fixtures/strings.rego
the following expression was parsed as an error:
```
a:= "\""
```
Fixes #97
=> grammar - string:  fix escape quote

hack/update-toc.sh, hack/verify-toc.sh
Correcting of spelling error in a comment.  No functional change.
=> Fix spelling of downloaded

SECURITY.md
This updates the link to open-policy-agent/opa/SECURITY.md to point to the main tree since that is the new default branch in that repo. It is not strictly necessary since GH is redirecting the old links appropriately.
=> docs: Update link to point to new default branch

src/main/kotlin/org/openpolicyagent/ideaplugin/ide/runconfig/producer/OpaEvalRunConfigurationProducer.kt, src/main/kotlin/org/openpolicyagent/ideaplugin/ide/runconfig/test/producer/OpaTestRunConfigurationProducer.kt
```release-note
Fix NPE when  loading project
```
Fixes #135
=> fix potential npe in producer when file is not a rego file

.github/workflows/test.yml, src/test/resources/org/openpolicyagent/ideaplugin/ide/actions/fmt/fixtures/already_formatted.rego, src/test/resources/org/openpolicyagent/ideaplugin/ide/actions/fmt/fixtures/already_formatted_after.rego
x-ref: https://github.com/open-policy-agent/opa-idea-plugin/pull/139#issuecomment-1367429724
=> Update CI OPA version

build.gradle.kts, gradle.properties
fix dependencies problem that failed the publishing  of the plugin
=> fix plugin dependencies

.github/workflows/test.yml, build.gradle.kts, gradle.properties, src/main/kotlin/org/openpolicyagent/ideaplugin/ide/runconfig/OpaEvalRunConfiguration.kt, src/main/kotlin/org/openpolicyagent/ideaplugin/ide/runconfig/test/OpaTestRunConfiguration.kt, src/main/kotlin/org/openpolicyagent/ideaplugin/ide/runconfig/test/ui/OpaTestRunCommandEditor.kt, src/main/kotlin/org/openpolicyagent/ideaplugin/ide/runconfig/ui/OpaEvalRunCommandEditor.kt, src/main/kotlin/org/openpolicyagent/ideaplugin/opa/project/settings/OpaOptionsConfigurable.kt, src/main/kotlin/org/openpolicyagent/ideaplugin/openapiext/utils.kt
This pr implements compatibility for 2023.3 (rc and over) and fix deprecated method usage warning. 
Fixes #163
```release-notes
Compatibility for ide 2023.3.
```
=> Compatibility 233

.github/workflows/release_and_pulbish_plugin_on_tag.yml, .github/workflows/test.yml, .github/workflows/upset_release_notes_pr_on_push_on_master.yml, hack/create_or_update_release_notes_pr.sh, hack/generate_release_notes.sh, hack/util.sh
=> Fix release note gen

.github/workflows/release_and_pulbish_plugin_on_tag.yml
=> update deprecated upload artifact action
