src/main/kotlin/org/openpolicyagent/ideaplugin/ide/actions/ActionUtils.kt
src/main/kotlin/org/openpolicyagent/ideaplugin/ide/actions/CheckAction.kt
src/main/kotlin/org/openpolicyagent/ideaplugin/ide/actions/FmtAction.kt
src/main/kotlin/org/openpolicyagent/ideaplugin/ide/actions/TestAction.kt
src/main/kotlin/org/openpolicyagent/ideaplugin/ide/actions/TestCoverageAction.kt
src/main/kotlin/org/openpolicyagent/ideaplugin/ide/extensions/OPAActionToolWindow.kt
src/main/kotlin/org/openpolicyagent/ideaplugin/opa/tool/OpaActions.kt
src/main/resources/META-INF/plugin.xml

-Created OpaActions utility class in opa.tool to hold implementation of actions rather than OpaCheck, OpaTest, etc files for each action piling up in opa.tool
-support for opa test, test coverage on project workspace and opa check on current open document, shows output in console window (all support for console window showing output is in extensions/OPAActionToolWindow)
fix #12

opa test workspace in console

---

docs/devel/architecture.md
src/main/kotlin/org/openpolicyagent/ideaplugin/ide/linemarkers/OpaCommandRunLineMarker.kt
src/main/kotlin/org/openpolicyagent/ideaplugin/ide/runconfig/OpaEvalRunConfiguration.kt
src/main/kotlin/org/openpolicyagent/ideaplugin/ide/runconfig/OpaEvalRunConfigurationType.kt
src/main/kotlin/org/openpolicyagent/ideaplugin/ide/runconfig/producer/OpaEvalRunConfigurationProducer.kt
src/main/kotlin/org/openpolicyagent/ideaplugin/ide/runconfig/test/OpaTestRunConfiguration.kt
src/main/kotlin/org/openpolicyagent/ideaplugin/ide/runconfig/test/OpaTestRunConfigurationType.kt
src/main/kotlin/org/openpolicyagent/ideaplugin/ide/runconfig/test/producer/OpaTestRunConfigurationProducer.kt
src/main/kotlin/org/openpolicyagent/ideaplugin/lang/psi/PsiElementExt.kt
src/main/kotlin/org/openpolicyagent/ideaplugin/lang/psi/PsiFileExt.kt
src/main/kotlin/org/openpolicyagent/ideaplugin/openapiext/ElementExt.kt
src/main/kotlin/org/openpolicyagent/ideaplugin/openapiext/utils.kt
src/main/resources/META-INF/plugin.xml
src/test/kotlin/org/openpolicyagent/ideaplugin/OpaTestBase.kt
src/test/kotlin/org/openpolicyagent/ideaplugin/ide/linemarkers/OpaCommandRunLineMarkerTest.kt
src/test/kotlin/org/openpolicyagent/ideaplugin/ide/linemarkers/OpaLineMarkerProviderTestBase.kt
src/test/kotlin/org/openpolicyagent/ideaplugin/ide/runconfig/producer/OpaEvalRunConfigurationProducerTest.kt
src/test/kotlin/org/openpolicyagent/ideaplugin/ide/runconfig/producer/RunConfigurationProducerTestBase.kt
src/test/kotlin/org/openpolicyagent/ideaplugin/ide/runconfig/test/OpaTestRunConfigurationProducerTest.kt
src/test/kotlin/org/openpolicyagent/ideaplugin/lang/RegoParsingTestCaseBase.kt
src/test/kotlin/org/openpolicyagent/ideaplugin/lang/psi/PsiElementExtKtTest.kt
src/test/kotlin/org/openpolicyagent/ideaplugin/lang/psi/PsiFileExtKtTest.kt
src/test/resources/org/openpolicyagent/ideaplugin/ide/runconfig/producer/fixtures/eval_producer_should_generate_config_to_eval_complex_rule.xml
src/test/resources/org/openpolicyagent/ideaplugin/ide/runconfig/producer/fixtures/eval_producer_should_generate_config_to_eval_package.xml
src/test/resources/org/openpolicyagent/ideaplugin/ide/runconfig/producer/fixtures/eval_should_generate_config_to_eval_eval_simple_rule.xml
src/test/resources/org/openpolicyagent/ideaplugin/ide/runconfig/producer/fixtures/test_producer_should_generate_config_for_test_rule.xml
src/test/resources/org/openpolicyagent/ideaplugin/ide/runconfig/producer/fixtures/test_producer_should_generate_config_to_test_package.xml

create LineRunMaker(green arrow)  on package and RuleHead. And 2 run configuration producer (one for eval and one for test) to create/edit the associated configuration
Most of the logic has been coded but some corner cases must still be addressed and tests must be added.
Fixes #28 #9 
It still in progress but if you want to test it. you must either comment or adapt these lines 
[OpaEvalRunConfigurationProducer.kt#L65-L66](https://github.com/vgramer/opa-idea-plugin/blob/4acdb35f6d80f5fd8b6d0a32aff715357982ba33/src/main/kotlin/org/openpolicyagent/ideaplugin/ide/runconfig/producer/OpaEvalRunConfigurationProducer.kt#L65-L66)
[OpaTestRunConfigurationProducer.kt#L59](https://github.com/vgramer/opa-idea-plugin/blob/4acdb35f6d80f5fd8b6d0a32aff715357982ba33/src/main/kotlin/org/openpolicyagent/ideap …

launch configuration from gutter

---

src/main/kotlin/org/openpolicyagent/ideaplugin/ide/runconfig/test/OpaTestEventsConverter.kt
src/test/kotlin/org/openpolicyagent/ideaplugin/ide/runconfig/test/OpaTestRunConfigurationBase.kt
src/test/resources/org/openpolicyagent/ideaplugin/ide/runconfig/test/runner_all_test_error/[root].regex
src/test/resources/org/openpolicyagent/ideaplugin/ide/runconfig/test/runner_with_all_tests_fail/[root].regex
src/test/resources/org/openpolicyagent/ideaplugin/ide/runconfig/test/runner_with_test_error_pass_and_fail/[root].regex
src/test/resources/org/openpolicyagent/ideaplugin/ide/runconfig/test/runner_with_test_pass_fail_and_error/[root].regex

Print the executed command and the full output on the root node.
Fixes #51

OpaTestRunConfiguration: add the full output of the command to the root node

---

src/main/grammar/Rego.bnf
src/test/resources/org/openpolicyagent/ideaplugin/lang/parser/fixtures/functions.rego

In rego this rule is valid:
```rego
fun_obj(x) = h {
h := {"a": {"b":  [x,2]}}
}
aRule {
a = fun_obj(1).a
}
```
but with the current grammar, nothing is allowed after an `expr-call`. So for your parser, this rule is not valid.
To fix that, we allow to have zero or more `ref-arg` (ie `"." var` or `"[" ( scalar | var | array | object | set | "_" ) "]"` => the accesor to an object or an array) after an `expr-call`
Fixes #57

fix grammar: access to function's return value without assigning it to a variable

---

src/main/grammar/Rego.bnf
src/test/resources/org/openpolicyagent/ideaplugin/lang/parser/fixtures/functions.rego

Fix bug in grammar that does not allow to use of infix operation as argument of a function 
Example:
This expression was reported as an error
```
ARule(){
x := count({x} & {y})
}
```
Also, add a test to check that function arg ca  be a complex expression (eg set comprehension, function call...)
Fixes #63

fix grammar: Operator inside of function args was reported as error

---

src/main/kotlin/org/openpolicyagent/ideaplugin/ide/colors/RegoColors.kt
src/main/kotlin/org/openpolicyagent/ideaplugin/ide/highlight/RegoHighlighterAnnotator.kt
src/main/kotlin/org/openpolicyagent/ideaplugin/lang/psi/RegoFile.kt
src/test/kotlin/org/openpolicyagent/ideaplugin/ide/highlight/AnnotatorTestBase.kt
src/test/kotlin/org/openpolicyagent/ideaplugin/ide/highlight/RegoHighlighterAnnotatorTest.kt
src/test/kotlin/org/openpolicyagent/ideaplugin/ide/highlight/TestSeverityProvider.kt

This Pr refactor and add tests on `RegoHighlighterAnnotator` 
Register RegoColors as new severities in order to test silent annotations

refactor RegoHighlighterAnnotator to make it testable

---

src/main/grammar/Rego.bnf
src/main/grammar/RegoLexer.flex
src/main/kotlin/org/openpolicyagent/ideaplugin/ide/highlight/AnnotatorBase.kt
src/main/kotlin/org/openpolicyagent/ideaplugin/ide/highlight/RegoHighlighterAnnotator.kt
src/main/kotlin/org/openpolicyagent/ideaplugin/ide/highlight/RegoSyntaxErrorAnnotator.kt
src/main/resources/META-INF/opa-core.xml
src/test/kotlin/org/openpolicyagent/ideaplugin/ide/highlight/AnnotatorTestBase.kt
src/test/kotlin/org/openpolicyagent/ideaplugin/ide/highlight/RegoHighlighterAnnotatorTest.kt
src/test/kotlin/org/openpolicyagent/ideaplugin/ide/highlight/RegoSyntaxErrorAnnotatorTest.kt
src/test/resources/org/openpolicyagent/ideaplugin/lang/parser/fixtures/strings.rego

In lexer, the closing quote for the string is optional in order to have a valid token, so the quoteHandler can autoclose it
if the user doesn't close the quote, an error will be reported by the RegoSyntaxErrorAnnotator
Introduce abstract class AnnotatorBase that adds annotation only if test mode is disabled or annotator is registered by the class under test. It allows having only the highlighting produce by the class under test in the test output
Fixes #
PR #73   need to be merge before in order to pass the tests. in the meantime this PR is draft

Fix grammar multiline quote

---

src/main/grammar/Rego.bnf
src/test/kotlin/org/openpolicyagent/ideaplugin/lang/RegoParsingTestCase.kt
src/test/resources/org/openpolicyagent/ideaplugin/lang/parser/fixtures/built_in_functions.rego
src/test/resources/org/openpolicyagent/ideaplugin/lang/parser/fixtures/rule_head.rego

Fix  the `rule-head` and `expr-infix`in the grammar
Only `term` was accepted in `rule-head`. Consequently, the following rule was invalid:
`a:= 1 + 2`
There were 2 problems:
* assignment was valid inside affectation (eg `a := b =  1 + 2`)
* only one infix operation was accepted. Consequently, this expression `a := 1 + 2 +3` was invalid
Fixes #70

grammar: fix rule-head and expr-infix

---

src/main/grammar/Rego.bnf
src/test/kotlin/org/openpolicyagent/ideaplugin/lang/RegoParsingTestCase.kt
src/test/resources/org/openpolicyagent/ideaplugin/lang/parser/fixtures/else_keyword.rego
src/test/resources/org/openpolicyagent/ideaplugin/lang/parser/fixtures/else_keyword_2.rego
src/test/resources/org/openpolicyagent/ideaplugin/lang/parser/fixtures/imports_between_rules.rego

Fix grammar to:
* allow imports between rules. Consequently, remove the useless grammar rule `policy`.
* allow `expr2` instead of `term` grammar rule in else statement
Fixes #76  
Fixes #78 
'else keyword' and 'else keyword 2' tests have been merged into 'else keyword' test

Fix grammar: allow import between rules and  complex expression in else statement

---

CONTRIBUTING.md
SECURITY.md
docs/devel/setup_development_env.md

this is required for migrating to open-policy-agent organization. see open-policy-agent/opa#3051

add security and DCO notice

---

.github/PULL_REQUEST_TEMPLATE.md
docs/devel/setup_development_env.md
plugin/src/main/resources/META-INF/plugin.xml

Remove references to old repo `vgramer/opa-idea-plugin`. The repository has been transferred to `open-policy-agent` organization
Fixes #
On [JetBrains Marketplace](https://plugins.jetbrains.com/plugin/14865-open-policy-agent), I have updated the link to the bug tracker, source code, and documentation. The vendor URL will be updated with the next release  of the plugin (This information comes from the plugin archive)

remove references to old repo vgramer/opa-idea-plugin

---

src/main/grammar/Rego.bnf
src/test/kotlin/org/openpolicyagent/ideaplugin/lang/RegoParsingTestCaseBase.kt
src/test/resources/org/openpolicyagent/ideaplugin/lang/parser/fixtures/else_keyword.rego

Fix 2 problems with else statement:
1.  previously: `else` must be followed by "{" query "}". Consequently, this valid code was reported as an error
```
package com.foo
foo = true {
input.x < input.y
} else = false
```
2. previously `else =` must be followed by `expr2`.  Consequently, this valid code was reported as an error
```
check_only_equal_querry_for_else = true {
false
} else = {
true
}
```
Fixes #84

fix grammar: allow empty query in else clause

---

src/main/grammar/Rego.bnf
src/test/kotlin/org/openpolicyagent/ideaplugin/lang/RegoParsingTestCase.kt
src/test/resources/org/openpolicyagent/ideaplugin/lang/parser/fixtures/factor_expr.rego

This PR adds the possibility to use factor expression (ie parenthesis )
The parsing of these expressions was failing:
```
a4:= (1 - 3)  * (2 +5)
reverse(l) = [l[j] | _ = l[i]; j := (count(l) - 1) - i]
```

Fix grammar: allow factor expression

---

src/main/grammar/Rego.bnf

`expr2` rule is  an  explicit name (i really wasn't inspired when I wrote it :/ )
This pr rename the grammar rule
- `expr` to `literal-expr`
- `expr2` to `expr`
if you have a better name in mind, I am open to suggestions.

refacror grammar: rename expr to literal-expr and expr2 to expr

---

gradle.properties
src/main/kotlin/org/openpolicyagent/ideaplugin/ide/runconfig/OpaEvalRunConfiguration.kt
src/main/kotlin/org/openpolicyagent/ideaplugin/ide/runconfig/OpaEvalRunProfileState.kt
src/main/kotlin/org/openpolicyagent/ideaplugin/ide/runconfig/test/OpaTestRunConfiguration.kt
src/main/kotlin/org/openpolicyagent/ideaplugin/ide/runconfig/test/OpaTestRunProfileState.kt
src/main/kotlin/org/openpolicyagent/ideaplugin/ide/runconfig/test/ui/OpaTestRunCommandEditor.kt
src/main/kotlin/org/openpolicyagent/ideaplugin/ide/runconfig/ui/OpaEvalRunCommandEditor.kt
src/test/kotlin/org/openpolicyagent/ideaplugin/ide/runconfig/OpaEvalRunConfigurationTest.kt
src/test/kotlin/org/openpolicyagent/ideaplugin/ide/runconfig/RunConfigurationTestBase.kt
src/test/kotlin/org/openpolicyagent/ideaplugin/ide/runconfig/test/OpaTestRunConfigurationBase.kt
src/test/kotlin/org/openpolicyagent/ideaplugin/ide/runconfig/test/OpaTestRunConfigurationTest.kt
src/test/resources/org/openpolicyagent/ideaplugin/ide/runconfig/producer/fixtures/eval_producer_should_generate_config_to_eval_complex_rule.xml
src/test/resources/org/openpolicyagent/ideaplugin/ide/runconfig/producer/fixtures/eval_producer_should_generate_config_to_eval_package.xml
src/test/resources/org/openpolicyagent/ideaplugin/ide/runconfig/producer/fixtures/eval_should_generate_config_to_eval_eval_simple_rule.xml
src/test/resources/org/openpolicyagent/ideaplugin/ide/runconfig/producer/fixtures/test_producer_should_generate_config_for_test_rule.xml
src/test/resources/org/openpolicyagent/ideaplugin/ide/runconfig/producer/fixtures/test_producer_should_generate_config_to_test_package.xml

- add option to configure env vars in eval/test config
- bump version for release to 0.7
Fixes #105

add option to configure env vars in eval/test config

---

gradle-211.properties

the version of `211.6305.21-EAP-SNAPSHOT` does not exist anymore.

gradle-211.properties: fix version of psiViewerPluginVersion

---

hack/generate_release_notes.sh

The GitHub workflow that generate release failed with the following error:
```
last release found. it's tag 'v0.7.0'
tag 'v0.7.0' point on commit 'a0ed8c28479c68e0e726e5d95efd11c51855d518'
level=info msg="Using output format: markdown"
level=info msg="Gathering release notes"
level=fatal msg="gathering release notes: listing release notes: listing commits: retrieve start commit: GET https://api.github.com/repos/open-policy-agent/opa-idea-plugin/git/commits/a0ed8c28479c68e0e726e5d95efd11c51855d518: 404 Not Found []"
Error: Process completed with exit code 1.
```
Contrary to old release tags the last one is an annotated tag. The `hack/generate_release_notes.sh` use the command `git rev-parse` to get the tagged commit's sha1. It works fine for "simple" tags but for annotated tags, it returns …

fix hack/generate_release_notes.sh: handle annotated tag

---

.github/workflows/test.yml
build.gradle.kts
gradle.properties
src/main/grammar/Rego.bnf
src/main/kotlin/org/openpolicyagent/ideaplugin/ide/highlight/RegoHighlighter.kt
src/test/resources/org/openpolicyagent/ideaplugin/lang/parser/fixtures/else_keyword.rego
src/test/resources/org/openpolicyagent/ideaplugin/lang/parser/fixtures/rule_head.rego

* Compatibility: upgrade to 2023.3 / 233.2 version
* Grammar: rules with multidimensional array heads support
* Grammar: else expressions no longer consider ':=' invalid
* tests: bump OPA version to v0.61.0
Fixes #165
Fixes #151

Support 2023.3 IDEA Version and Fix Minor Error False Positives

---

gradle.properties

Make this plugin compatible with newer JetBrains versions. Tested locally on GoLand 2024.2.
Simple compatibility marker update.

Make compatible with newer Jetbrains versions

---

build.gradle.kts
gradle.properties
src/main/resources/META-INF/opa-core.xml

```release-notes
* compatibity 2024.3
* move `new rego file` action to lower division
```
Fixes #179 #178 
I though migration to IntelliJ platform Gradle plugin v2.0 was necessary for 243 but it is not. I still have some issue with the migration. However, as it is not a requirement for 243, we can take care of the migration after the release. I created #182 to keep track.

compatibility IDE 243 and move new rego file action to lower division
